### ISSUE TITLE
Please provision a recent (at least 20.3.x) OTP version by default

### ISSUE THREAD

**Issue by michaelklishin** [sous-chefs/erlang#61]
### Cookbook version

12.x, 13.x

### Chef-client version

12.x, 13.x

### Platform Details

All.

### Scenario:

Trying to provision an Erlang/OTP version which is reasonably up-to-date.

OTP 18.x and 19.x up to 19.3.6.4 are known to have major issues that affect servers that use TCP, e.g.
[ERL-430](https://bugs.erlang.org/browse/ERL-430) and [ERL-448](https://bugs.erlang.org/browse/ERL-448).

Dependent cookbooks such as RabbitMQ currently have to provide explicit instructions for this
cookbook so that a reasonably stable OTP version is guaranteed to be installed.

It would be really nice if this cookbook provisioned 20.2.x or at least 19.3.6.5 by default,
e.g. using the ESL installation method. I do recognize that it would be a breaking change
and would meet some opposition but for the next major version, it's the Right Thing to Do™.

### Steps to Reproduce:

Add `erlang::default` to run list without modifying any node attributes.

### Expected Result:

A reasonably recent (20.3.8 or later) version is provisioned if possible.

### Actual Result:

An older version is provisioned (at best 19.2).

**Comment by michaelklishin** [comment]
Any feedback on this idea? Is this something this cookbook's maintainers would accept if contributed?

**Comment by majormoses** [comment]
@tas50 that seems fine though if we are crossing major versions we should probably do it in a major version bump to avoid potentially breaking users.

**Comment by michaelklishin** [comment]
Erlang is at `21.2.x` already, provisioning `19.2` by default seems odd at this point. A major version bump makes some sense.

**Comment by michaelklishin** [comment]
One of the solutions to the lack of modern Erlang patch/version availability can be #67.

**Comment by majormoses** [comment]
I am not a maintainer for this cookbook but this seems sane to me, I commented on your other issue about bintray. When you have a PR I am more than happy to look at it and provide feedback.
